fix: Remove references to history and HISTORY.rst as HISTORY.rst does not exist
This fixes the package install failure:

```
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/philroche/Working/oval-xml-feed-merge/setup.py", line 10, in <module>
          with open("HISTORY.rst") as history_file:
               ^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [Errno 2] No such file or directory: 'HISTORY.rst'
      [end of output]

```